//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFClient.ServiceReference1.ResultOfGroupQo1Oyztf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFClient.ServiceReference1.ResultOfActiveSessionQo1Oyztf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFClient.ServiceReference1.ResultOfArrayOfGroupInviteQo1Oyztf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFClient.ServiceReference1.ResultOfArrayOfintuHEDJ7Dj))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFClient.ServiceReference1.ResultOfArrayOfGroupQo1Oyztf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFClient.ServiceReference1.ResultOfArrayOfUserQo1Oyztf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFClient.ServiceReference1.ResultOfArrayOfActiveSessionQo1Oyztf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFClient.ServiceReference1.ResultOfUserQo1Oyztf))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFClient.ServiceReference1.ResultError ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFClient.ServiceReference1.ResultError Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfGroupQo1Oyztf", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class ResultOfGroupQo1Oyztf : WCFClient.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFClient.ServiceReference1.Group DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFClient.ServiceReference1.Group Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfActiveSessionQo1Oyztf", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class ResultOfActiveSessionQo1Oyztf : WCFClient.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFClient.ServiceReference1.ActiveSession DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFClient.ServiceReference1.ActiveSession Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfArrayOfGroupInviteQo1Oyztf", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class ResultOfArrayOfGroupInviteQo1Oyztf : WCFClient.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFClient.ServiceReference1.GroupInvite[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFClient.ServiceReference1.GroupInvite[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfArrayOfintuHEDJ7Dj", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class ResultOfArrayOfintuHEDJ7Dj : WCFClient.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfArrayOfGroupQo1Oyztf", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class ResultOfArrayOfGroupQo1Oyztf : WCFClient.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFClient.ServiceReference1.Group[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFClient.ServiceReference1.Group[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfArrayOfUserQo1Oyztf", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class ResultOfArrayOfUserQo1Oyztf : WCFClient.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFClient.ServiceReference1.User[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFClient.ServiceReference1.User[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfArrayOfActiveSessionQo1Oyztf", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class ResultOfArrayOfActiveSessionQo1Oyztf : WCFClient.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFClient.ServiceReference1.ActiveSession[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFClient.ServiceReference1.ActiveSession[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfUserQo1Oyztf", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class ResultOfUserQo1Oyztf : WCFClient.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFClient.ServiceReference1.User DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFClient.ServiceReference1.User Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultError", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    public enum ResultError : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameIsUsed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordIsIncorrect = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorOnMessage = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotExist = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Null = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Service.DTO")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/Service.DTO")]
    [System.SerializableAttribute()]
    public partial class Group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] MembersIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFClient.ServiceReference1.User OwnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOwner {
            get {
                return this.IsOwnerField;
            }
            set {
                if ((this.IsOwnerField.Equals(value) != true)) {
                    this.IsOwnerField = value;
                    this.RaisePropertyChanged("IsOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] MembersIds {
            get {
                return this.MembersIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.MembersIdsField, value) != true)) {
                    this.MembersIdsField = value;
                    this.RaisePropertyChanged("MembersIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFClient.ServiceReference1.User Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Service.DTO")]
    [System.SerializableAttribute()]
    public partial class ActiveSession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MulticastAddresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((this.GroupIdField.Equals(value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MulticastAddres {
            get {
                return this.MulticastAddresField;
            }
            set {
                if ((object.ReferenceEquals(this.MulticastAddresField, value) != true)) {
                    this.MulticastAddresField = value;
                    this.RaisePropertyChanged("MulticastAddres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupInvite", Namespace="http://schemas.datacontract.org/2004/07/Service.DTO")]
    [System.SerializableAttribute()]
    public partial class GroupInvite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFClient.ServiceReference1.User FromUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FromUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFClient.ServiceReference1.Group ToGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToGroupIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFClient.ServiceReference1.User FromUser {
            get {
                return this.FromUserField;
            }
            set {
                if ((object.ReferenceEquals(this.FromUserField, value) != true)) {
                    this.FromUserField = value;
                    this.RaisePropertyChanged("FromUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FromUserId {
            get {
                return this.FromUserIdField;
            }
            set {
                if ((this.FromUserIdField.Equals(value) != true)) {
                    this.FromUserIdField = value;
                    this.RaisePropertyChanged("FromUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFClient.ServiceReference1.Group ToGroup {
            get {
                return this.ToGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.ToGroupField, value) != true)) {
                    this.ToGroupField = value;
                    this.RaisePropertyChanged("ToGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToGroupId {
            get {
                return this.ToGroupIdField;
            }
            set {
                if ((this.ToGroupIdField.Equals(value) != true)) {
                    this.ToGroupIdField = value;
                    this.RaisePropertyChanged("ToGroupId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService", CallbackContract=typeof(WCFClient.ServiceReference1.IServiceCallback))]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        WCFClient.ServiceReference1.ResultOfUserQo1Oyztf Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Login", ReplyAction="http://tempuri.org/IService/LoginResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfUserQo1Oyztf> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Register", ReplyAction="http://tempuri.org/IService/RegisterResponse")]
        WCFClient.ServiceReference1.ResultOfUserQo1Oyztf Register(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Register", ReplyAction="http://tempuri.org/IService/RegisterResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfUserQo1Oyztf> RegisterAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateGroup", ReplyAction="http://tempuri.org/IService/CreateGroupResponse")]
        WCFClient.ServiceReference1.ResultOfGroupQo1Oyztf CreateGroup(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateGroup", ReplyAction="http://tempuri.org/IService/CreateGroupResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfGroupQo1Oyztf> CreateGroupAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Logout", ReplyAction="http://tempuri.org/IService/LogoutResponse")]
        WCFClient.ServiceReference1.Result Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Logout", ReplyAction="http://tempuri.org/IService/LogoutResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.Result> LogoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendGroupInvite", ReplyAction="http://tempuri.org/IService/SendGroupInviteResponse")]
        WCFClient.ServiceReference1.Result SendGroupInvite(string groupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendGroupInvite", ReplyAction="http://tempuri.org/IService/SendGroupInviteResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.Result> SendGroupInviteAsync(string groupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AcceptGroupInvite", ReplyAction="http://tempuri.org/IService/AcceptGroupInviteResponse")]
        WCFClient.ServiceReference1.Result AcceptGroupInvite(int inviteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AcceptGroupInvite", ReplyAction="http://tempuri.org/IService/AcceptGroupInviteResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.Result> AcceptGroupInviteAsync(int inviteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CancelGroupInvite", ReplyAction="http://tempuri.org/IService/CancelGroupInviteResponse")]
        WCFClient.ServiceReference1.Result CancelGroupInvite(int inviteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CancelGroupInvite", ReplyAction="http://tempuri.org/IService/CancelGroupInviteResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.Result> CancelGroupInviteAsync(int inviteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/StartSession", ReplyAction="http://tempuri.org/IService/StartSessionResponse")]
        WCFClient.ServiceReference1.ResultOfActiveSessionQo1Oyztf StartSession(string name, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/StartSession", ReplyAction="http://tempuri.org/IService/StartSessionResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfActiveSessionQo1Oyztf> StartSessionAsync(string name, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/JoinSession", ReplyAction="http://tempuri.org/IService/JoinSessionResponse")]
        WCFClient.ServiceReference1.ResultOfActiveSessionQo1Oyztf JoinSession(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/JoinSession", ReplyAction="http://tempuri.org/IService/JoinSessionResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfActiveSessionQo1Oyztf> JoinSessionAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGroupsInvites", ReplyAction="http://tempuri.org/IService/GetGroupsInvitesResponse")]
        WCFClient.ServiceReference1.ResultOfArrayOfGroupInviteQo1Oyztf GetGroupsInvites();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGroupsInvites", ReplyAction="http://tempuri.org/IService/GetGroupsInvitesResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfArrayOfGroupInviteQo1Oyztf> GetGroupsInvitesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserGroupsIds", ReplyAction="http://tempuri.org/IService/GetUserGroupsIdsResponse")]
        WCFClient.ServiceReference1.ResultOfArrayOfintuHEDJ7Dj GetUserGroupsIds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserGroupsIds", ReplyAction="http://tempuri.org/IService/GetUserGroupsIdsResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfArrayOfintuHEDJ7Dj> GetUserGroupsIdsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGroups", ReplyAction="http://tempuri.org/IService/GetGroupsResponse")]
        WCFClient.ServiceReference1.ResultOfArrayOfGroupQo1Oyztf GetGroups(int[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGroups", ReplyAction="http://tempuri.org/IService/GetGroupsResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfArrayOfGroupQo1Oyztf> GetGroupsAsync(int[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUsers", ReplyAction="http://tempuri.org/IService/GetUsersResponse")]
        WCFClient.ServiceReference1.ResultOfArrayOfUserQo1Oyztf GetUsers(int[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUsers", ReplyAction="http://tempuri.org/IService/GetUsersResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfArrayOfUserQo1Oyztf> GetUsersAsync(int[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetActiveSessionById", ReplyAction="http://tempuri.org/IService/GetActiveSessionByIdResponse")]
        WCFClient.ServiceReference1.ResultOfActiveSessionQo1Oyztf GetActiveSessionById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetActiveSessionById", ReplyAction="http://tempuri.org/IService/GetActiveSessionByIdResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfActiveSessionQo1Oyztf> GetActiveSessionByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetActiveSessions", ReplyAction="http://tempuri.org/IService/GetActiveSessionsResponse")]
        WCFClient.ServiceReference1.ResultOfArrayOfActiveSessionQo1Oyztf GetActiveSessions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetActiveSessions", ReplyAction="http://tempuri.org/IService/GetActiveSessionsResponse")]
        System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfArrayOfActiveSessionQo1Oyztf> GetActiveSessionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/OnSessionStarted")]
        void OnSessionStarted(WCFClient.ServiceReference1.ActiveSession session);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/OnActiveSessionUpdated")]
        void OnActiveSessionUpdated(WCFClient.ServiceReference1.ActiveSession activeSession);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/OnGroupInvitesUpdated")]
        void OnGroupInvitesUpdated(WCFClient.ServiceReference1.GroupInvite[] groupInvites);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/OnGroupListUpdated")]
        void OnGroupListUpdated(WCFClient.ServiceReference1.Group[] groups);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WCFClient.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.DuplexClientBase<WCFClient.ServiceReference1.IService>, WCFClient.ServiceReference1.IService {
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public WCFClient.ServiceReference1.ResultOfUserQo1Oyztf Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfUserQo1Oyztf> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public WCFClient.ServiceReference1.ResultOfUserQo1Oyztf Register(string username, string password) {
            return base.Channel.Register(username, password);
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfUserQo1Oyztf> RegisterAsync(string username, string password) {
            return base.Channel.RegisterAsync(username, password);
        }
        
        public WCFClient.ServiceReference1.ResultOfGroupQo1Oyztf CreateGroup(string name) {
            return base.Channel.CreateGroup(name);
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfGroupQo1Oyztf> CreateGroupAsync(string name) {
            return base.Channel.CreateGroupAsync(name);
        }
        
        public WCFClient.ServiceReference1.Result Logout() {
            return base.Channel.Logout();
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.Result> LogoutAsync() {
            return base.Channel.LogoutAsync();
        }
        
        public WCFClient.ServiceReference1.Result SendGroupInvite(string groupName) {
            return base.Channel.SendGroupInvite(groupName);
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.Result> SendGroupInviteAsync(string groupName) {
            return base.Channel.SendGroupInviteAsync(groupName);
        }
        
        public WCFClient.ServiceReference1.Result AcceptGroupInvite(int inviteId) {
            return base.Channel.AcceptGroupInvite(inviteId);
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.Result> AcceptGroupInviteAsync(int inviteId) {
            return base.Channel.AcceptGroupInviteAsync(inviteId);
        }
        
        public WCFClient.ServiceReference1.Result CancelGroupInvite(int inviteId) {
            return base.Channel.CancelGroupInvite(inviteId);
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.Result> CancelGroupInviteAsync(int inviteId) {
            return base.Channel.CancelGroupInviteAsync(inviteId);
        }
        
        public WCFClient.ServiceReference1.ResultOfActiveSessionQo1Oyztf StartSession(string name, int groupId) {
            return base.Channel.StartSession(name, groupId);
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfActiveSessionQo1Oyztf> StartSessionAsync(string name, int groupId) {
            return base.Channel.StartSessionAsync(name, groupId);
        }
        
        public WCFClient.ServiceReference1.ResultOfActiveSessionQo1Oyztf JoinSession(int id) {
            return base.Channel.JoinSession(id);
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfActiveSessionQo1Oyztf> JoinSessionAsync(int id) {
            return base.Channel.JoinSessionAsync(id);
        }
        
        public WCFClient.ServiceReference1.ResultOfArrayOfGroupInviteQo1Oyztf GetGroupsInvites() {
            return base.Channel.GetGroupsInvites();
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfArrayOfGroupInviteQo1Oyztf> GetGroupsInvitesAsync() {
            return base.Channel.GetGroupsInvitesAsync();
        }
        
        public WCFClient.ServiceReference1.ResultOfArrayOfintuHEDJ7Dj GetUserGroupsIds() {
            return base.Channel.GetUserGroupsIds();
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfArrayOfintuHEDJ7Dj> GetUserGroupsIdsAsync() {
            return base.Channel.GetUserGroupsIdsAsync();
        }
        
        public WCFClient.ServiceReference1.ResultOfArrayOfGroupQo1Oyztf GetGroups(int[] ids) {
            return base.Channel.GetGroups(ids);
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfArrayOfGroupQo1Oyztf> GetGroupsAsync(int[] ids) {
            return base.Channel.GetGroupsAsync(ids);
        }
        
        public WCFClient.ServiceReference1.ResultOfArrayOfUserQo1Oyztf GetUsers(int[] ids) {
            return base.Channel.GetUsers(ids);
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfArrayOfUserQo1Oyztf> GetUsersAsync(int[] ids) {
            return base.Channel.GetUsersAsync(ids);
        }
        
        public WCFClient.ServiceReference1.ResultOfActiveSessionQo1Oyztf GetActiveSessionById(int id) {
            return base.Channel.GetActiveSessionById(id);
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfActiveSessionQo1Oyztf> GetActiveSessionByIdAsync(int id) {
            return base.Channel.GetActiveSessionByIdAsync(id);
        }
        
        public WCFClient.ServiceReference1.ResultOfArrayOfActiveSessionQo1Oyztf GetActiveSessions() {
            return base.Channel.GetActiveSessions();
        }
        
        public System.Threading.Tasks.Task<WCFClient.ServiceReference1.ResultOfArrayOfActiveSessionQo1Oyztf> GetActiveSessionsAsync() {
            return base.Channel.GetActiveSessionsAsync();
        }
    }
}
